name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Build
    steps:
    - uses: actions/checkout@v2

    - name: Get Previous tag
      id: latest_tag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 0.0.0

    - name: Extract branch name
      id: extract_branch
      shell: bash
      run: |
        RawBranch="$(echo ${GITHUB_REF#refs/heads/})"
        echo "##[set-output name=branch;]$(echo $RawBranch)"

    - uses: ./.github/workflows/pipeline/builder
      with:
        version: ${{ steps.latest_tag.outputs.tag }}-${{ steps.extract_branch.outputs.branch }}
