name: Build

on:
  push:
    branches:
      - '**'

jobs:
  macOS:
    runs-on: macos-latest
    environment: Build
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Setup Certificates
      uses: apple-actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
        keychain: github-actions-xamarin
        keychain-password: ""

    - name: Setup Provisioning Profiles
      uses: apple-actions/download-provisioning-profiles@v1
      with:
        bundle-id: 'com.julian-baumann.InterShareDesktop'
        profile-type: 'MAC_APP_STORE'
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

    - name: Restore
      run: |
        dotnet restore src/DesktopApp/DesktopApp.csproj
        nuget restore src/DesktopApp.XamMac/DesktopApp.XamMac.csproj

    - name: Build
      env:
        PROJECT_NAME: "InterShare"
        MAC_APP_FILE: "InterShare.app"
        MAC_PROJECT_DIR: "./src/DesktopApp.XamMac"
        MAC_PROJECT_FILE: "DesktopApp.XamMac.csproj"
        BUILD_OUTPUT_DIRECTORY: ${{ github.workspace }}/build
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
      run: ./.github/workflows/scripts/build-mac.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: macOS-Build
        path: ${{ github.workspace }}/build
